name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
          php-version: 7.2
    - name: Run tests
      run: composer test
